name: app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  # default
  get: 4.6.5
  flutter_gen: ^5.2.0
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.6.0
  material_color_generator: ^1.1.0
  dio: ^4.0.6
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.16
  intl: ^0.18.1
  dropdown_button2: ^2.1.0
  image_picker: ^0.8.6+1
  lottie: ^2.3.2
  toggle_switch: ^2.1.0
  url_launcher: ^6.1.10
  flutter_countdown_timer: ^4.1.0
  carousel_slider: ^4.2.1
  pinput: ^2.2.21
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  avatar_glow: ^2.0.2
  google_fonts:

  flutter:
    sdk: flutter
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # default
  build_runner:
  flutter_gen_runner:
flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/iconsc/
